camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks

springdoc:
  api-docs:
    path: "/api-docs"

statemachine:
  to-load: "OnboardingPoc"
  rest-host: "http://localhost:8080/engine-rest"
  get-task-id: "/task"
  complete-task: "/task/{task_id}/complete"
  start: "/process-definition/key/{key}/start"
  state-with-back: "WAIT_PERSONAL_DATA"
  state-with-retry: "ISSUE_CARD_EXCEPTION"

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
    ddl-auto: none



#spring:
#  jersey:
#    application-path: "/statemachine"